Repository Dariusionut/user-management, pull requests merged in 2023-04, with the labels that each got.

#3 Feature/darius
  README.md
  src/main/resources/templates/home.html
  src/main/resources/templates/users.html
Labels: enhancement

#21 Develop
  .gitignore
  pom.xml
  src/main/java/com/spring/studentmanagement/controllers/HomeController.java
  src/main/java/com/spring/studentmanagement/controllers/UserController.java
  src/main/java/com/spring/studentmanagement/models/Role.java
  src/main/resources/application-datasource.yaml
  src/main/resources/application.yaml
  src/main/resources/static/scripts/handlers.js
  src/main/resources/templates/fragments/dialogs.html
  src/main/resources/templates/fragments/head-fragments.html
  src/main/resources/templates/home.html
  src/main/resources/templates/users.html
Labels: Delliver

#30 I have done the logo
  .gitignore
  src/main/java/com/spring/studentmanagement/models/AppUser.java
  src/main/resources/db/scripts.sql
  src/main/resources/static/images/logo.png
  src/main/resources/templates/fragments/navbar-fragments.html
Labels: Development

#32 Merged changes from develop to main
  src/main/java/com/spring/studentmanagement/models/AppUser.java
  src/main/resources/static/images/logo.png
  src/main/resources/templates/fragments/navbar-fragments.html
Labels: Delliver

#33 29 update user html view
  src/main/resources/templates/user.html
  src/main/resources/templates/users.html
Labels: Development

#36 Updated home
  src/main/resources/templates/index.html
Labels: Development

#35 Added login VIEW
  src/main/java/com/spring/studentmanagement/controllers/UserController.java
  src/main/resources/templates/login.html
Labels: Development

#44 26 sign up
  src/main/java/com/spring/studentmanagement/controllers/HomeController.java
  src/main/java/com/spring/studentmanagement/controllers/UserController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/register.html
Labels: Development

#45 I added the address entity!
  src/main/java/com/spring/studentmanagement/controllers/HomeController.java
  src/main/java/com/spring/studentmanagement/models/Address.java
  src/main/java/com/spring/studentmanagement/models/AppUser.java
  src/main/resources/db/01_reset.sql
  src/main/resources/db/02_table_role.sql
  src/main/resources/db/03_table_address.sql
  src/main/resources/db/04_table_app_user.sql
  src/main/resources/db/scripts.sql
Labels: question, Refactor

#48 Develop
  src/main/java/com/spring/studentmanagement/controllers/HomeController.java
  src/main/java/com/spring/studentmanagement/controllers/UserController.java
  src/main/java/com/spring/studentmanagement/models/Address.java
  src/main/java/com/spring/studentmanagement/models/AppUser.java
  src/main/resources/db/01_reset.sql
  src/main/resources/db/02_table_role.sql
  src/main/resources/db/03_table_address.sql
  src/main/resources/db/04_table_app_user.sql
  src/main/resources/db/scripts.sql
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/register.html
  src/main/resources/templates/user.html
  src/main/resources/templates/users.html
Labels: Delliver

#50 I added fix-address-relation!
  src/main/resources/db/03_table_address.sql
  src/main/resources/db/04_table_app_user.sql
Labels: Development

#51 12 create profiles
  pom.xml
  src/main/java/com/spring/studentmanagement/models/Address.java
  src/main/java/com/spring/studentmanagement/models/AppUser.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application.yaml
  src/test/java/com/spring/studentmanagement/StudentManagementApplicationTests.java
  src/test/java/com/spring/studentmanagement/StudentManagementTest.java
  src/test/java/com/spring/studentmanagement/controllers/UserControllerTest.java
  src/test/java/com/spring/studentmanagement/services/UserServiceImplTest.java
  src/test/resources/application-test.yaml
Labels: Development

#52 I added fix-address-relation!
  src/main/resources/db/03_table_address.sql
  src/main/resources/db/04_table_app_user.sql
Labels: Development

#54 27 secure user passwords
  pom.xml
  src/main/java/com/spring/studentmanagement/security/SecurityConfig.java
  src/main/java/com/spring/studentmanagement/services/UserService.java
  src/main/java/com/spring/studentmanagement/services/UserServiceImpl.java
  src/main/resources/db/03_table_address.sql
Labels: Development

#56 added a Terms of Service page
  src/main/java/com/spring/studentmanagement/controllers/HomeController.java
  src/main/resources/templates/register.html
  src/main/resources/templates/terms.html
Labels: Development

#62 57-error 403
  src/main/java/com/spring/studentmanagement/controllers/ErrorController.java
  src/main/resources/templates/errors/error-403.html
Labels: Development

#63 58 page status error
  src/main/java/com/spring/studentmanagement/controllers/ErrorController.java
  src/main/resources/templates/errors/error-status.html
  src/test/java/com/spring/studentmanagement/controllers/ErrorControllerTest.java
Labels: Development

#64 61 register new account
  src/main/java/com/spring/studentmanagement/controllers/UserController.java
Labels: help wanted

#70 69 is enabled fix
  src/main/java/com/spring/studentmanagement/dto/SignUpRequestDto.java
Labels: Fix

#71 Develop
  .github/workflows/codeql.yml
  pom.xml
  src/main/java/com/spring/studentmanagement/controllers/AuthController.java
  src/main/java/com/spring/studentmanagement/controllers/ErrorController.java
  src/main/java/com/spring/studentmanagement/controllers/HomeController.java
  src/main/java/com/spring/studentmanagement/controllers/UserController.java
  src/main/java/com/spring/studentmanagement/dto/SignUpRequestDto.java
  src/main/java/com/spring/studentmanagement/models/AppUser.java
  src/main/java/com/spring/studentmanagement/repositories/RoleRepository.java
  src/main/java/com/spring/studentmanagement/security/AppAuthenticationManagerImpl.java
  src/main/java/com/spring/studentmanagement/security/SecurityConfig.java
  src/main/java/com/spring/studentmanagement/security/SecurityServiceImpl.java
  src/main/java/com/spring/studentmanagement/security/UserDetailsServiceImpls.java
  src/main/java/com/spring/studentmanagement/security/filters/AuthFilter.java
  src/main/java/com/spring/studentmanagement/security/interfaces/AppAuthManager.java
  src/main/java/com/spring/studentmanagement/security/interfaces/AppUserDetailsService.java
  src/main/java/com/spring/studentmanagement/security/interfaces/SecurityService.java
  src/main/java/com/spring/studentmanagement/services/UserService.java
  src/main/java/com/spring/studentmanagement/services/UserServiceImpl.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/static/styles/register.css
  src/main/resources/templates/errors/error-401.html
  src/main/resources/templates/fragments/head-fragments.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/register.html
  src/main/resources/templates/user.html
  src/main/resources/templates/users.html
  src/test/java/com/spring/studentmanagement/controllers/UserControllerTest.java
Labels: Delliver

#73 We need logout funtionality
  src/main/java/com/spring/studentmanagement/controllers/UserController.java
  src/main/resources/templates/users.html
Labels: Development

#74 Added Course and CourseCategory Entity (sql and classes)
  src/main/java/com/spring/studentmanagement/controllers/CourseController.java
  src/main/java/com/spring/studentmanagement/exceptions/CourseNotFoundException.java
  src/main/java/com/spring/studentmanagement/models/Course.java
  src/main/java/com/spring/studentmanagement/models/CourseCategory.java
  src/main/java/com/spring/studentmanagement/repositories/CourseRepository.java
  src/main/java/com/spring/studentmanagement/services/CourseService.java
  src/main/java/com/spring/studentmanagement/services/CourseServiceImpl.java
  src/main/resources/db/01_reset.sql
  src/main/resources/db/05_table_course_category.sql
  src/main/resources/db/06_table_course.sql
Labels: Development

#81 Redesigned and refactored code for the login.html
  src/main/resources/static/styles/login.css
  src/main/resources/templates/fragments/head-fragments.html
  src/main/resources/templates/login.html
Labels: Redesign UI

#83 Course view and course view functionality
  src/main/java/com/spring/studentmanagement/controllers/CourseController.java
  src/main/java/com/spring/studentmanagement/models/Course.java
  src/main/resources/templates/courses.html
Labels: Development

#87 I redesigned the error page and renamed the file error-500.html
  src/main/java/com/spring/studentmanagement/controllers/ErrorController.java
  src/main/resources/templates/errors/error-500.html
  src/main/resources/templates/errors/error-status.html
  src/test/java/com/spring/studentmanagement/controllers/ErrorControllerTest.java
Labels: Development

#88 77 redesign error 403 page
  src/main/resources/static/styles/errors.css
  src/main/resources/templates/errors/error-403.html
Labels: Development

#89 76 redesign error 401 page
  src/main/resources/static/styles/errors.css
  src/main/resources/templates/errors/error-401.html
  src/main/resources/templates/errors/error-403.html
Labels: Development

#93 92 update security
  pom.xml
  src/main/java/com/spring/studentmanagement/controllers/UserController.java
  src/main/java/com/spring/studentmanagement/security/AppHttpServletRequestWrapper.java
  src/main/java/com/spring/studentmanagement/security/AppPrincipalImpl.java
  src/main/java/com/spring/studentmanagement/security/filters/AuthFilter.java
  src/main/java/com/spring/studentmanagement/security/interfaces/AppPrincipal.java
  src/main/java/com/spring/studentmanagement/security/services/SecurityServiceImpl.java
  src/main/java/com/spring/studentmanagement/security/services/UserDetailsServiceImpls.java
  src/main/resources/templates/users.html
  src/test/java/com/spring/studentmanagement/controllers/UserControllerTest.java
Labels: Development, Security, Sprint 2

#96 Added a Back link
  src/main/resources/templates/forgot.html
Labels: Development

#97 Redesigned the 401, 403 and 500 error views
  src/main/resources/static/styles/errors.css
  src/main/resources/static/styles/global.css
  src/main/resources/templates/errors/error-401.html
  src/main/resources/templates/errors/error-403.html
  src/main/resources/templates/errors/error-500.html
Labels: Redesign UI

#98 95 secured /courses endpoint
  src/main/java/com/spring/studentmanagement/security/SecurityConfig.java
Labels: Fix
